import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { createPlaylist, SpotifyNotLinkedError } from "@/lib/spotify";

export const runtime = "nodejs";

export async function POST(req: Request) {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: {
    name?: string;
    description?: string;
    uris?: string[];
    isPublic?: boolean;
  };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const uris = (body.uris || []).filter((u) => typeof u === "string");
  if (uris.length === 0) {
    return NextResponse.json({ error: "No tracks to add." }, { status: 400 });
  }

  try {
    const result = await createPlaylist(session.user.id, {
      name: body.name?.trim() || "AI Blended Playlist",
      description: body.description?.trim() || "Generated by Spotify Playlist Builder.",
      uris,
      isPublic: Boolean(body.isPublic),
    });
    return NextResponse.json(result);
  } catch (err) {
    if (err instanceof SpotifyNotLinkedError) {
      return NextResponse.json(
        { error: "Spotify account not linked." },
        { status: 412 }
      );
    }
    console.error("playlist error", err);
    return NextResponse.json(
      { error: "Failed to create playlist." },
      { status: 500 }
    );
  }
}
